[package]
name = "ymx-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
yaml-rust2.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
indexmap = { workspace = true, features = ["serde"] }
ryu.workspace = true
